package com.bank.taskallocationexample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Assignment implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Assignment() {
    }




}